# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18  
          registry-url: "https://registry.npmjs.org"
    
      - name: Publish in npm
        run: npm ci
        run: npm --no-git-tag-version version ${{ github.event.release.tag_name }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
